[platformio]
boards_dir = ../boards/pio

[env]
platform = espressif32
board_build.variants_dir = ../boards/variants

lib_deps =
    ftswarm-core=symlink://../ftswarm-core
    pololu/VL53L0X@^1.3.1
    electroniccats/MPU6050@^1.4.1
    olikraus/U8g2 @ ^2.35.19
    stm32duino/STM32duino LSM6DSR@^2.2.0
    makuna/NeoPixelBus@^2.8.4

framework = arduino

build_flags =
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DARDUINO_RUNNING_CORE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=1

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
upload_speed = 921600

debug_tool = esp-prog
debug_init_break = tbreak setup


[env:firmware-control-usbc]
board = ftSwarmControlUSBC

[env:firmware-control-usbmicro]
board = ftSwarmControlUSBMicro

[env:firmware-duino]
board = ftSwarmDuino

[env:firmware-jst]
board = ftSwarmJST

[env:firmware-rc]
board = ftSwarmRC

[env:firmware-rs]
board = ftSwarmRS

[env:firmware-xl]
board = ftSwarmXL

[env:firmware-pwrdrive]
board = ftSwarmPwrDrive

