/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FTSWARM_FTSWARM_PB_H_INCLUDED
#define PB_FTSWARM_FTSWARM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ftSwarm_version {
    ftSwarm_version_JST_1V0 = 0,
    ftSwarm_version_CONTROL_1V3 = 1,
    ftSwarm_version_JST_1V15 = 2,
    ftSwarm_version_RS_2V0 = 3,
    ftSwarm_version_RS_2V1 = 4,
    ftSwarm_version_CAM_3V12 = 5,
    ftSwarm_version_DUINO_1V141 = 6,
    ftSwarm_version_PWRDRIVE_1V141 = 7,
    ftSwarm_version_XL_1V00 = 8,
    ftSwarm_version_RC_1V140 = 9
} ftSwarm_version;

/* Struct definitions */
typedef struct _ftSwarm_Controller {
    pb_callback_t x;
    bool has_serialNumber;
    int32_t serialNumber;
    bool has_cpu;
    ftSwarm_version cpu;
} ftSwarm_Controller;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ftSwarm_version_MIN ftSwarm_version_JST_1V0
#define _ftSwarm_version_MAX ftSwarm_version_RC_1V140
#define _ftSwarm_version_ARRAYSIZE ((ftSwarm_version)(ftSwarm_version_RC_1V140+1))

#define ftSwarm_Controller_cpu_ENUMTYPE ftSwarm_version


/* Initializer values for message structs */
#define ftSwarm_Controller_init_default          {{{NULL}, NULL}, false, 0, false, _ftSwarm_version_MIN}
#define ftSwarm_Controller_init_zero             {{{NULL}, NULL}, false, 0, false, _ftSwarm_version_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ftSwarm_Controller_x_tag                 1
#define ftSwarm_Controller_serialNumber_tag      2
#define ftSwarm_Controller_cpu_tag               3

/* Struct field encoding specification for nanopb */
#define ftSwarm_Controller_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   x,                 1) \
X(a, STATIC,   OPTIONAL, INT32,    serialNumber,      2) \
X(a, STATIC,   OPTIONAL, UENUM,    cpu,               3)
#define ftSwarm_Controller_CALLBACK pb_default_field_callback
#define ftSwarm_Controller_DEFAULT NULL

extern const pb_msgdesc_t ftSwarm_Controller_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ftSwarm_Controller_fields &ftSwarm_Controller_msg

/* Maximum encoded size of messages (where known) */
/* ftSwarm_Controller_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
