import { SwOSIOType } from "./generated/genApiEnums";

export const FtSwarmIoTypeNames: Record<SwOSIOType, string> = {
  [SwOSIOType.SWOSIO_UNDEF]: "",
  [SwOSIOType.SWOSIO_DIGITAL]: "Digital Input",
  [SwOSIOType.SWOSIO_SWITCH]: "Switch",
  [SwOSIOType.SWOSIO_REEDSWITCH]: "Reed Switch",
  [SwOSIOType.SWOSIO_LIGHTBARRIER]: "Light Barrier",
  [SwOSIOType.SWOSIO_BUTTON]: "Button",
  [SwOSIOType.SWOSIO_ANALOG]: "Analog Input",
  [SwOSIOType.SWOSIO_VOLTMETER]: "Voltmeter",
  [SwOSIOType.SWOSIO_OHMMETER]: "Ohmmeter",
  [SwOSIOType.SWOSIO_THERMOMETER]: "Thermometer",
  [SwOSIOType.SWOSIO_LDR]: "Photoresistor (LDR)",
  [SwOSIOType.SWOSIO_JOYSTICK]: "Joystick",
  [SwOSIOType.SWOSIO_MOTOR]: "Motor",
  [SwOSIOType.SWOSIO_XSMOTOR]: "XS Motor",
  [SwOSIOType.SWOSIO_XMMOTOR]: "XM Motor",
  [SwOSIOType.SWOSIO_TRACTOR]: "Tractor Motor",
  [SwOSIOType.SWOSIO_ENCODER]: "Encoder Motor",
  [SwOSIOType.SWOSIO_LAMP]: "Lamp",
  [SwOSIOType.SWOSIO_VALVE]: "Valve",
  [SwOSIOType.SWOSIO_COMPRESSOR]: "Compressor",
  [SwOSIOType.SWOSIO_BUZZER]: "Buzzer",
  [SwOSIOType.SWOSIO_STEPPER]: "Stepper Motor",
  [SwOSIOType.SWOSIO_COUNTER]: "Counter",
  [SwOSIOType.SWOSIO_ROTARYENCODER]: "Rotary Encoder",
  [SwOSIOType.SWOSIO_FREQUENCYMETER]: "Frequency Meter",
  [SwOSIOType.SWOSIO_LIDAR]: "Lidar Sensor",
  [SwOSIOType.SWOSIO_CAM]: "Camera",
  [SwOSIOType.SWOSIO_SERVO]: "Servo Motor",
  [SwOSIOType.SWOSIO_PIXEL]: "ftPixel",
  [SwOSIOType.SWOSIO_OLED]: "Display",
  [SwOSIOType.SWOSIO_I2C]: "I2C Device",
  [SwOSIOType.SWOSIO_GYRO]: "Gyroscope",
  [SwOSIOType.SWOSIO_HC165]: "Shift Register (HC165)",
  [SwOSIOType.SWOSIO_POWER]: "Power Meter",
  [SwOSIOType.SWOSIO_COLORSENSOR]: "Color Sensor",
  [SwOSIOType.SWOSIO_TRAILSENSOR]: "Trail Sensor",
  [SwOSIOType.SWOSIO_ULTRASONIC]: "Ultrasonic Sensor",
  [SwOSIOType.SWOSIO_JOYSTICK_POTI]: "Joystick Potentiometer",
  [SwOSIOType.SWOSIO_WHEELDRIVE]: "Wheel Drive",
  [SwOSIOType.SWOSIO_MINIMOTOR]: "Mini Motor",
  [SwOSIOType.SWOSIO_SMOTOR]: "S Motor",
  [SwOSIOType.SWOSIO_POWERMOTOR]: "Power Motor",
  [SwOSIOType.SWOSIO_MMOTOR]: "M Motor",
  [SwOSIOType.SWOSIO_MAXIOTYPE]: "",
};
