
/**
 * @file sfs_files.h
 * @brief File list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script 
 *       in /dashboard. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

extern const char *sfs_get_file( char *filename, uint32_t *length );


// //index.html  SHA1:d33e191d3150538f917da9688b6702d8785e65c2
extern const char sfs_index_html[];
#define SFS_index_html_len 303

// /assets/02_switch.svg  SHA1:f88a014da19950a4839cf83abaf4cf7b17dfe176
extern const char sfs_assets_02_switch_svg[];
#define SFS_02_switch_svg_len 802

// /assets/06_ntc.svg  SHA1:b3b79545811780add3424e8ebccdcb91dd90c01b
extern const char sfs_assets_06_ntc_svg[];
#define SFS_06_ntc_svg_len 754

// /assets/05_resistor.svg  SHA1:1e6babeb7bb6e092e2b090acf145969c63a53924
extern const char sfs_assets_05_resistor_svg[];
#define SFS_05_resistor_svg_len 1115

// /assets/16_xmotor.svg  SHA1:bb72f4a94af92b63057049faf187db0ff8c4ba07
extern const char sfs_assets_16_xmotor_svg[];
#define SFS_16_xmotor_svg_len 2616

// /assets/09_colorsensor.svg  SHA1:d6700c72e8d5b1347d97965f22139afbc2e114af
extern const char sfs_assets_09_colorsensor_svg[];
#define SFS_09_colorsensor_svg_len 989

// /assets/21_lightbarrier.svg  SHA1:9036fc8d6b5e105e74d94a73c3934b35fc500038
extern const char sfs_assets_21_lightbarrier_svg[];
#define SFS_21_lightbarrier_svg_len 1163

// /assets/22_compressor.svg  SHA1:1d397903c7a2648248080566c1364c17c95e39b4
extern const char sfs_assets_22_compressor_svg[];
#define SFS_22_compressor_svg_len 843

// /assets/13_motor.svg  SHA1:a3cfb9452f93d1f465da691772f2cbfc3da1fa71
extern const char sfs_assets_13_motor_svg[];
#define SFS_13_motor_svg_len 806

// /assets/18_encoder.svg  SHA1:eea6b1195e085b81426b86098c0ed41d82271cd5
extern const char sfs_assets_18_encoder_svg[];
#define SFS_18_encoder_svg_len 2571

// /assets/08_trailsensor.svg  SHA1:5ea4efc8a2d5e044be6089cdb95231e97f03c4df
extern const char sfs_assets_08_trailsensor_svg[];
#define SFS_08_trailsensor_svg_len 911

// /assets/ftSwarm-927930a8.svg  SHA1:e91a3612b7ac951ccf6bb2f04a9d3e15cc6e4c1e
extern const char sfs_assets_ftSwarm_927930a8_svg[];
#define SFS_ftSwarm_927930a8_svg_len 2701

// /assets/index-853c5ed3.js  SHA1:fddd57e967203f444a65ba3ecd26e570d82ab253
extern const char sfs_assets_index_853c5ed3_js[];
#define SFS_index_853c5ed3_js_len 30369

// /assets/03_reedswitch.svg  SHA1:b475e820acce50763f054b4bcdcaded0fe02ecb1
extern const char sfs_assets_03_reedswitch_svg[];
#define SFS_03_reedswitch_svg_len 1603

// /assets/24_buzzer.svg  SHA1:8049652c18b853798390ad439e61f359d853a3c3
extern const char sfs_assets_24_buzzer_svg[];
#define SFS_24_buzzer_svg_len 1576

// /assets/23_valve.svg  SHA1:8c3e9f248e8303b7d28a22db88463d7cfc6562e7
extern const char sfs_assets_23_valve_svg[];
#define SFS_23_valve_svg_len 1007

// /assets/12_button.svg  SHA1:ba05d1d423d417be137118e02ebc70264803acf9
extern const char sfs_assets_12_button_svg[];
#define SFS_12_button_svg_len 878

// /assets/14_servo.svg  SHA1:290780470b71b0c7d62355c82f95711bd0a7c995
extern const char sfs_assets_14_servo_svg[];
#define SFS_14_servo_svg_len 1125

// /assets/10_ultrasonic.svg  SHA1:cea98fde55ec37412ba49a289d35410df617542d
extern const char sfs_assets_10_ultrasonic_svg[];
#define SFS_10_ultrasonic_svg_len 1633

// /assets/19_lamp.svg  SHA1:9e0f53290843c368874e6403fc7627c673aef271
extern const char sfs_assets_19_lamp_svg[];
#define SFS_19_lamp_svg_len 801

// /assets/07_ldr.svg  SHA1:399af455673ebdfea4be506605d22dd0a10b0c30
extern const char sfs_assets_07_ldr_svg[];
#define SFS_07_ldr_svg_len 1118

// /assets/15_rgbled.svg  SHA1:c57fc58de72baadf8eb5a1310ccb98e1b866aaa9
extern const char sfs_assets_15_rgbled_svg[];
#define SFS_15_rgbled_svg_len 974

// /assets/00_digital.svg  SHA1:ab174fb78ea7588e92b46ef323659784e5edadf0
extern const char sfs_assets_00_digital_svg[];
#define SFS_00_digital_svg_len 722

// /assets/20_xmmotor.svg  SHA1:6bd9975a58008f4b4452b2668d6b7afa7ba6557d
extern const char sfs_assets_20_xmmotor_svg[];
#define SFS_20_xmmotor_svg_len 2606

// /assets/favicon.ico  SHA1:2d362f559723acf2e1033e1c45f6ae67853699a9
extern const char sfs_assets_favicon_ico[];
#define SFS_favicon_ico_len 1279

// /assets/index-b078bf7b.css  SHA1:5c0d6073010ae1816d47a47ff4ab06b50da8619e
extern const char sfs_assets_index_b078bf7b_css[];
#define SFS_index_b078bf7b_css_len 1534

// /assets/11_joystick.svg  SHA1:f35741e978ce4b0884d92a136a388991edc9d1a3
extern const char sfs_assets_11_joystick_svg[];
#define SFS_11_joystick_svg_len 1434

// /assets/01_analog.svg  SHA1:9db3ac01b3b86bb6f5eba27405d121e32181bb85
extern const char sfs_assets_01_analog_svg[];
#define SFS_01_analog_svg_len 1029

// /assets/17_tractor.svg  SHA1:2fea905a1009daef6a0798b371cd6a116552b846
extern const char sfs_assets_17_tractor_svg[];
#define SFS_17_tractor_svg_len 2542

// /assets/04_voltage.svg  SHA1:71e8652cad157dd4e85f02e29417dd1e94b341b9
extern const char sfs_assets_04_voltage_svg[];
#define SFS_04_voltage_svg_len 868
