export enum FtSwarmIOType {
    UNDEF = -1,
    INPUT,
    DIGITALINPUT,
    ANALOGINPUT,
    ACTOR,
    BUTTON,
    JOYSTICK,
    PIXEL,
    SERVO,
    OLED,
    GYRO,
    HC165,
    I2C,
    CAM,
    COUNTERINPUT,
    ROTARYINPUT,
    FREQUENCYINPUT,
    MAXIOTYPE
}

export enum FtSwarmActor {
    MOTOR,
    XMMOTOR,
    TRACTOR,
    ENCODER,
    LAMP,
    VALVE,
    COMPRESSOR,
    BUZZER,
    STEPPER,
    MAXACTOR
}

export const ACTOR_NAMES = [
    "MOTOR",
    "XMMOTOR",
    "TRACTOR",
    "ENCODER",
    "LAMP",
    "VALVE",
    "COMPRESSOR",
    "BUZZER",
    "STEPPER",
]


export enum FtSwarmSensor {
    DIGITAL,
    ANALOG,
    SWITCH,
    REEDSWITCH,
    LIGHTBARRIER,
    VOLTMETER,
    OHMMETER,
    THERMOMETER,
    LDR,
    TRAILSENSOR,
    COLORSENSOR,
    ULTRASONIC,
    CAMSENSOR,
    COUNTER,
    ROTARYENCODER,
    FREQUENCYMETER,
    LIDAR
}

export const SENSOR_NAMES = [
    "DIGITAL",
    "ANALOG",
    "SWITCH",
    "REEDSWITCH",
    "LIGHTBARRIER",
    "VOLTMETER",
    "OHMMETER",
    "THERMOMETER",
    "LDR",
    "TRAILSENSOR",
    "COLORSENSOR",
    "ULTRASONIC",
    "CAMSENSOR",
    "COUNTER",
    "ROTARYENCODER",
    "FREQUENCYMETER",
    "LIDAR"
]

export const ICONS = [
    "00_digital.svg",
    "01_analog.svg",
    "02_switch.svg",
    "03_reedswitch.svg",
    "04_voltage.svg",
    "05_resistor.svg",
    "06_ntc.svg",
    "07_ldr.svg",
    "08_trailsensor.svg",
    "09_colorsensor.svg",
    "10_ultrasonic.svg",
    "11_joystick.svg",
    "12_button.svg",
    "13_motor.svg",
    "14_servo.svg",
    "15_rgbled.svg",
    "16_xmotor.svg",
    "17_tractor.svg",
    "18_encoder.svg",
    "19_lamp.svg",
    "20_xmmotor.svg",
    "21_lightbarrier.svg",
    "22_compressor.svg",
    "23_valve.svg",
    "24_buzzer.svg",
    "25_counter.svg",
    "26_cam.svg",
    "27_rotaryencoder.svg",
    "28_frequency.svg",
    "29_gyro.svg",
]