import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIST_DIR = new URL('dist/', import.meta.url).pathname;
const OUT_H = new URL('../ftswarm-core/include/sfs_files.h', import.meta.url).pathname;
const OUT_CPP = new URL('../ftswarm-core/src/sfs_files.cpp', import.meta.url).pathname;

const brFiles = readdirSync(DIST_DIR).filter(f => f.endsWith('.br'));

function pathToIdent(filepath: string): string {
  let name = filepath.replace(/^\/+/, '').replace(/\.br$/, '');
  name = name.replace(/[-.]+/g, '_');
  if (!name.startsWith('_')) name = '_' + name;
  return 'sfs' + name;
}

function pathToPathname(filepath: string): string {
  return '/' + filepath.replace(/^\/+/, '');
}

interface FileInfo {
  pathname: string;
  data: Buffer;
  ident: string;
  length: number;
  sha1: string;
}

const files: FileInfo[] = [];

for (const fn of brFiles) {
  const data = readFileSync(join(DIST_DIR, fn));
  const sha1 = createHash('sha1').update(data).digest('hex');
  const ident = pathToIdent(fn);
  const pathname = pathToPathname(fn);
  files.push({ pathname, data, ident, length: data.length, sha1 });
}

// --- generate header ---
const hLines: string[] = [];
hLines.push('');
hLines.push('/**');
hLines.push(' * @file sfs_files.h');
hLines.push(' * @brief Brotli-compressed file list for the Web Server');
hLines.push(' * @long This file contains the list of files that are available on the Web Server. It is generated by the build script');
hLines.push(' *       in /src/ide. It is not intended to be modified by the user.');
hLines.push(' */');
hLines.push('');
hLines.push('#pragma once');
hLines.push('#include <stdint.h>');
hLines.push('');

for (const f of files) {
  const lenMacro = f.ident + '_br_len';
  hLines.push(`// ${f.pathname}  SHA1:${f.sha1}`);
  hLines.push(`extern const char ${f.ident}_br[];`);
  hLines.push(`#define ${lenMacro} ${f.length}`);
  hLines.push('');
}

writeFileSync(OUT_H, hLines.join('\n'));
console.log(`wrote ${OUT_H}`);

// --- generate cpp ---
const cppLines: string[] = [];
cppLines.push('');
cppLines.push('/**');
cppLines.push(' * @file sfs_files.cpp');
cppLines.push(' * @brief Brotli-compressed file list for the Web Server');
cppLines.push(' * @long This file contains the list of files that are available on the Web Server. It is generated by the build script');
cppLines.push(' *       in /src/ide. It is not intended to be modified by the user.');
cppLines.push(' */');
cppLines.push('');
cppLines.push('#include "sfs_files.h"');
cppLines.push('#include <stdint.h>');
cppLines.push('#include <string.h>');
cppLines.push('');

for (const f of files) {
  cppLines.push(`const char ${f.ident}_br[] = {`);
  const d = f.data;
  for (let i = 0; i < d.length; i += 16) {
    const chunk = d.subarray(i, i + 16);
    const hex = [...chunk].map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ');
    cppLines.push('    ' + hex + ',');
  }
  cppLines.push('};');
  cppLines.push('');
}

writeFileSync(OUT_CPP, cppLines.join('\n'));
console.log(`wrote ${OUT_CPP}`);
