#!/usr/bin/env python3
"""Update the ftSwarm library version and build its PlatformIO package."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEVELOP_DIR = SCRIPT_DIR.parent
LIBRARY_DIR = DEVELOP_DIR / "src" / "ftswarm-core"
LIBRARY_JSON = LIBRARY_DIR / "library.json"
BUILD_DIR = DEVELOP_DIR / "build"
VERSION_FILE = DEVELOP_DIR / "build" / "swos_version.txt"
PIO_STARTER_DIR = DEVELOP_DIR / "src" / "platform" / "pio-starter"


def get_version(version_argument: str | None) -> str:
    """Get the requested version or use the version generated by build.py."""
    if version_argument:
        return version_argument

    if not VERSION_FILE.exists():
        raise FileNotFoundError(
            f"Version file not found: {VERSION_FILE}. Pass a version argument "
            "or run build.py first."
        )

    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not version:
        raise ValueError(f"Version file is empty: {VERSION_FILE}")
    return version


def update_library_version(version: str) -> None:
    """Validate library.json and update its top-level version field."""
    data = json.loads(LIBRARY_JSON.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {LIBRARY_JSON}")

    data["version"] = version
    LIBRARY_JSON.write_text(
        json.dumps(data, indent=4) + "\n",
        encoding="utf-8",
    )


def build_package(version: str) -> Path:
    """Build the package archive using the expected publisher/name filename."""
    package_path = BUILD_DIR / f"elektrofuzzis-ftSwarm-{version}.tar.gz"
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["pio", "pkg", "pack", "--output", str(package_path)],
        cwd=str(LIBRARY_DIR),
        check=True,
    )
    return package_path


def build_pio_starter_zip(version: str) -> Path:
    """Create a versioned ZIP archive containing the pio-starter directory."""
    if not PIO_STARTER_DIR.is_dir():
        raise FileNotFoundError(f"PIO starter directory not found: {PIO_STARTER_DIR}")

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    archive_base = BUILD_DIR / f"pio-starter-{version}"
    archive_path = Path(
        shutil.make_archive(
            str(archive_base),
            "zip",
            root_dir=str(PIO_STARTER_DIR.parent),
            base_dir=PIO_STARTER_DIR.name,
        )
    )
    return archive_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build the ftSwarm PlatformIO library package."
    )
    parser.add_argument(
        "version",
        nargs="?",
        help="Package version; defaults to build/swos_version.txt.",
    )
    args = parser.parse_args()

    version = get_version(args.version)
    update_library_version(version)
    print(f"Updated {LIBRARY_JSON} to version {version}")
    package_path = build_package(version)
    print(f"Package archive written to {package_path}")
    starter_archive = build_pio_starter_zip(version)
    print(f"PIO starter archive written to {starter_archive}")


if __name__ == "__main__":
    try:
        main()
    except (FileNotFoundError, ValueError, subprocess.CalledProcessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)