#!/usr/bin/env python3
"""Build firmware for all ftSwarm environments using PlatformIO.

This script:
1. Reads version from build/swos_version.txt (generated by build.py)
2. Uses platformio.ini from the scripts folder to identify environments
3. Builds firmware for each environment using `pio run -e <env>`
4. Stores compiled binaries in build/firmware/ with naming convention:
   - {env}-{version}-{binary}.bin for environments ending with "-de"
   - {env}-en-{version}-{binary}.bin for other environments
5. Binary files: firmware.bin, bootloader.bin, partitions.bin

Usage:
    python build-firmware.py
    
Prerequisites:
    - PlatformIO CLI must be installed (pio command available)
    - scripts/platformio.ini must exist
    - build/swos_version.txt must exist (created by build.py)
"""

from __future__ import annotations

import configparser
import os
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEVELOP_DIR = SCRIPT_DIR.parent
FTSWARM_RS_DIR = SCRIPT_DIR
BUILD_DIR = DEVELOP_DIR / "build"
BUILD_FIRMWARE_DIR = BUILD_DIR / "firmware"
VERSION_FILE = BUILD_DIR / "swos_version.txt"
PLATFORMIO_INI = FTSWARM_RS_DIR / "platformio.ini"

# Binary files to copy
BIN_FILES = ["firmware.bin", "bootloader.bin", "partitions.bin"]


def get_version() -> str:
    """Read version from build/swos_version.txt."""
    if not VERSION_FILE.exists():
        raise FileNotFoundError(
            f"Version file not found: {VERSION_FILE}\n"
            "Run build.py first to generate the version file."
        )
    return VERSION_FILE.read_text(encoding="utf-8").strip()


def get_platformio_envs() -> list[str]:
    """Read all environments from platformio.ini."""
    if not PLATFORMIO_INI.exists():
        raise FileNotFoundError(f"PlatformIO config not found: {PLATFORMIO_INI}")
    
    config = configparser.ConfigParser()
    config.read(PLATFORMIO_INI)
    
    envs = [
        section.replace("env:", "")
        for section in config.sections()
        if section.startswith("env:") and section != "env"
    ]
    
    if not envs:
        raise ValueError(f"No environments found in {PLATFORMIO_INI}")
    
    return sorted(envs)


def build_environment(env: str) -> bool:
    """Build a specific environment using PlatformIO."""
    print(f"\nBuilding environment: {env}")
    print("=" * 60)
    
    result = subprocess.run(
        ["pio", "run", "-e", env],
        cwd=str(FTSWARM_RS_DIR),
        capture_output=False
    )
    
    if result.returncode != 0:
        print(f"ERROR: Build failed for environment '{env}'")
        return False
    
    return True


def get_output_filename(env: str, version: str, binary: str) -> str:
    """Generate output filename following naming convention.
    
    Convention:
    - {env}-{version}-{binary} if env ends with "-de"
    - {env}-en-{version}-{binary} otherwise
    """
    if env.endswith("-de"):
        return f"{env}-{version}-{binary}"
    else:
        return f"{env}-en-{version}-{binary}"


def copy_binaries(env: str, version: str) -> bool:
    """Copy built binaries to build/firmware directory."""
    build_dir = FTSWARM_RS_DIR / ".pio" / "build" / env
    
    if not build_dir.exists():
        print(f"WARNING: Build directory not found: {build_dir}")
        return False
    
    copied_any = False
    
    for binary_file in BIN_FILES:
        source_bin = build_dir / binary_file
        
        if not source_bin.exists():
            print(f"  WARNING: {binary_file} not found in {build_dir}")
            continue
        
        output_filename = get_output_filename(env, version, binary_file)
        target_bin = BUILD_FIRMWARE_DIR / output_filename
        
        shutil.copy2(source_bin, target_bin)
        print(f"  Copied: {output_filename}")
        copied_any = True
    
    return copied_any


def main() -> None:
    print("ftSwarm Firmware Build Tool")
    print("=" * 60)
    
    # Get version
    try:
        version = get_version()
        print(f"Version: {version}")
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Get environments
    try:
        envs = get_platformio_envs()
        print(f"Environments: {', '.join(envs)}")
    except (FileNotFoundError, ValueError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Prepare output directory
    BUILD_FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Output directory: {BUILD_FIRMWARE_DIR}")
    
    # Check PlatformIO availability
    result = subprocess.run(["pio", "--version"], capture_output=True, text=True)
    if result.returncode != 0:
        print("ERROR: PlatformIO CLI not found. Please install it first.", file=sys.stderr)
        print("  Install with: pip install platformio", file=sys.stderr)
        sys.exit(1)
    
    print(f"PlatformIO: {result.stdout.strip()}")
    
    # Build each environment
    failed_envs = []
    successful_envs = []
    
    for env in envs:
        try:
            if not build_environment(env):
                failed_envs.append(env)
                continue
            
            if not copy_binaries(env, version):
                print(f"  WARNING: No binaries copied for {env}")
            else:
                successful_envs.append(env)
        
        except Exception as e:
            print(f"  ERROR: Exception during build: {e}", file=sys.stderr)
            failed_envs.append(env)
    
    # Summary
    print("\n" + "=" * 60)
    print("Build Summary")
    print("=" * 60)
    
    if successful_envs:
        print(f"Successful ({len(successful_envs)}): {', '.join(successful_envs)}")
    
    if failed_envs:
        print(f"Failed ({len(failed_envs)}): {', '.join(failed_envs)}", file=sys.stderr)
        sys.exit(1)
    
    print(f"\nAll firmware builds completed successfully!")
    print(f"Output: {BUILD_FIRMWARE_DIR}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
