[platformio]
boards_dir = ../src/platform/pio-starter/boards/pio

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
    ftswarm-core=symlink://../../develop/src/ftswarm-core
    pololu/VL53L0X
    electroniccats/MPU6050
    stm32duino/STM32duino LSM6DSR
    fastled/FastLED
    olikraus/U8g2

board_build.variants_dir = ../src/platform/pio-starter/boards/variants
monitor_filters = esp32_exception_decoder

[env:ftSwarmRS]
board = ftSwarmRS

[env:ftSwarmRS-de]
board = ftSwarmRS
build_flags = -D LANGUAGEDE

[env:ftSwarmRC]
board = ftSwarmRC

[env:ftSwarmRC-de]
board = ftSwarmRC
build_flags = -D LANGUAGEDE

[env:ftSwarmJST]
board = ftSwarmJST

[env:ftSwarmJST-de]
board = ftSwarmJST
build_flags = -D LANGUAGEDE

[env:ftSwarmXL]
board = ftSwarmXL

[env:ftSwarmXL-de]
board = ftSwarmXL
build_flags = -D LANGUAGEDE

[env:ftSwarmControlUSBC]
board = ftSwarmControlUSBC

[env:ftSwarmControlUSBC-de]
board = ftSwarmControlUSBC
build_flags = -D LANGUAGEDE

[env:ftSwarmControlUSBMicro]
board = ftSwarmControlUSBMicro

[env:ftSwarmControlUSBMicro-de]
board = ftSwarmControlUSBMicro
build_flags = -D LANGUAGEDE

[env:ftSwarmPwrDrive]
board = ftSwarmPwrDrive

[env:ftSwarmPwrDrive-de]
board = ftSwarmPwrDrive
build_flags = -D LANGUAGEDE

[env:ftSwarmDuino]
board = ftSwarmDuino

[env:ftSwarmDuino-de]
board = ftSwarmDuino
build_flags = -D LANGUAGEDE
