
/**
 * @file sfs_files.h
 * @brief File list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script 
 *       in /panel. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

extern const char *sfs_get_file( char *filename, uint32_t *length );


// //index.html  SHA1:37a5e507c26ba59b20f6f80ba57c395689146b82
extern const char sfs_index_html[];
#define SFS_index_html_len 375

// /assets/05_resistor.svg  SHA1:f6a296c2036617c7d395ddda9742452684728f0d
extern const char sfs_assets_05_resistor_svg[];
#define SFS_05_resistor_svg_len 1120

// /assets/19_lamp.svg  SHA1:682ec1beee5573b0b0b53bbedd08c758bf2db82d
extern const char sfs_assets_19_lamp_svg[];
#define SFS_19_lamp_svg_len 806

// /assets/02_switch.svg  SHA1:c98261d7fba14d036d8a07d97c58161a88044849
extern const char sfs_assets_02_switch_svg[];
#define SFS_02_switch_svg_len 806

// /assets/17_tractor.svg  SHA1:0d9aab92089c2c29445c19f04eace7abd17fa5e9
extern const char sfs_assets_17_tractor_svg[];
#define SFS_17_tractor_svg_len 2549

// /assets/09_colorsensor.svg  SHA1:a95f115b2313482dd12d74795dcdc43c8c60536d
extern const char sfs_assets_09_colorsensor_svg[];
#define SFS_09_colorsensor_svg_len 996

// /assets/00_digital.svg  SHA1:f170c59c9c99db0bfc3084cd346fb875c0fecc85
extern const char sfs_assets_00_digital_svg[];
#define SFS_00_digital_svg_len 729

// /assets/08_trailsensor.svg  SHA1:7609700ea93fbfb85d84232a9cc91e3c32d18225
extern const char sfs_assets_08_trailsensor_svg[];
#define SFS_08_trailsensor_svg_len 915

// /assets/16_xmotor.svg  SHA1:02d66859d34439dc999730cf91ffeeffb216e56d
extern const char sfs_assets_16_xmotor_svg[];
#define SFS_16_xmotor_svg_len 2624

// /assets/04_voltage.svg  SHA1:42770ea6af72d58c9213697c7ee65c8554559d09
extern const char sfs_assets_04_voltage_svg[];
#define SFS_04_voltage_svg_len 874

// /assets/01_analog.svg  SHA1:b96d89ccb641a7949661bdc1a7d0d4140d490909
extern const char sfs_assets_01_analog_svg[];
#define SFS_01_analog_svg_len 1033

// /assets/18_encoder.svg  SHA1:dc9ad40f13ac4fe6424b00299858175fb145d4ff
extern const char sfs_assets_18_encoder_svg[];
#define SFS_18_encoder_svg_len 2579

// /assets/14_servo.svg  SHA1:afa9c33ca9f1e9316a3636511608a0d14ce4a630
extern const char sfs_assets_14_servo_svg[];
#define SFS_14_servo_svg_len 1129

// /assets/03_reedswitch.svg  SHA1:9036cb2ee056d317a451879b2c6216c241dbb116
extern const char sfs_assets_03_reedswitch_svg[];
#define SFS_03_reedswitch_svg_len 1612

// /assets/11_joystick.svg  SHA1:60b72e1fe11144a7ec886b217599abf2b4943aa7
extern const char sfs_assets_11_joystick_svg[];
#define SFS_11_joystick_svg_len 1438

// /assets/15_rgbled.svg  SHA1:03fb11403a9baa100083e983be727bd90c65fa2b
extern const char sfs_assets_15_rgbled_svg[];
#define SFS_15_rgbled_svg_len 981

// /assets/12_button.svg  SHA1:c6a066064b87fa544557d7e302ef15439e7730bb
extern const char sfs_assets_12_button_svg[];
#define SFS_12_button_svg_len 882

// /assets/07_ldr.svg  SHA1:007e5161145b7b8ff8558957ff70f6a5610ace42
extern const char sfs_assets_07_ldr_svg[];
#define SFS_07_ldr_svg_len 1124

// /assets/ftSwarm.svg  SHA1:ff2c3ffd2268889292d33e2a3c5a783d907c5875
extern const char sfs_assets_ftSwarm_svg[];
#define SFS_ftSwarm_svg_len 2731

// /assets/06_ntc.svg  SHA1:d036b5f2a1a2118fa7c93109d51d00d305bf0b26
extern const char sfs_assets_06_ntc_svg[];
#define SFS_06_ntc_svg_len 756

// /assets/10_ultrasonic.svg  SHA1:af86c136d95c97afc2b8d42fbbb67a430cc10a17
extern const char sfs_assets_10_ultrasonic_svg[];
#define SFS_10_ultrasonic_svg_len 1641

// /assets/13_motor.svg  SHA1:85cbdecb65d4752e7b006459083da18bfb3516cb
extern const char sfs_assets_13_motor_svg[];
#define SFS_13_motor_svg_len 814

// /assets/ftSwarm.bmp  SHA1:d5117b9868ea03fc854a44267681fa35e6a32e5b
extern const char sfs_assets_ftSwarm_bmp[];
#define SFS_ftSwarm_bmp_len 311

// /css/app.f7a62135.css  SHA1:0ce87c3e53c13298351dced1ab12f40dad64a357
extern const char sfs_css_app_f7a62135_css[];
#define SFS_app_f7a62135_css_len 1190

// /js/app.15085054.js.map  SHA1:3936451e4b83fcd0dfbd10f9507b8a695afcace7
extern const char sfs_js_app_15085054_js_map[];
#define SFS_app_15085054_js_map_len 12267

// /js/app.15085054.js  SHA1:196bdfa0f3bdeb4b3a7e92090ffc2d328fe8bab0
extern const char sfs_js_app_15085054_js[];
#define SFS_app_15085054_js_len 4771

// /js/chunk-vendors.8f68e716.js  SHA1:b8146848d0a0ed43a08520108ee08b3f10de295f
extern const char sfs_js_chunk_vendors_8f68e716_js[];
#define SFS_chunk_vendors_8f68e716_js_len 45739

// /js/chunk-vendors.8f68e716.js.map  SHA1:bcfe7e2e4970ecd0c3cee3edc1cac067eba6cbf3
extern const char sfs_js_chunk_vendors_8f68e716_js_map[];
#define SFS_chunk_vendors_8f68e716_js_map_len 214422
