
/**
 * @file sfs_files.h
 * @brief File list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script 
 *       in /dashboard. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

extern const char *sfs_get_file( char *filename, uint32_t *length );


// //index.html  SHA1:d60255bc301715939108b1281d160617b4a2af36
extern const char sfs_index_html[];
#define SFS_index_html_len 308

// /assets/00_digital.svg  SHA1:10d9268066ce1b8e4bd0dc7096dd51c5ab290c1e
extern const char sfs_assets_00_digital_svg[];
#define SFS_00_digital_svg_len 729

// /assets/01_analog.svg  SHA1:cc472e4c88daf27fa13fcc290c016dac73dc90ab
extern const char sfs_assets_01_analog_svg[];
#define SFS_01_analog_svg_len 1033

// /assets/02_switch.svg  SHA1:09e3391643539b38f6be419597c954b672fe7dfd
extern const char sfs_assets_02_switch_svg[];
#define SFS_02_switch_svg_len 806

// /assets/03_reedswitch.svg  SHA1:f23280c142df96ae7141faab1ba35f00a13b6d04
extern const char sfs_assets_03_reedswitch_svg[];
#define SFS_03_reedswitch_svg_len 1612

// /assets/04_voltage.svg  SHA1:5b04d1587ff01a3b447c8f10dbf3306989f61949
extern const char sfs_assets_04_voltage_svg[];
#define SFS_04_voltage_svg_len 874

// /assets/05_resistor.svg  SHA1:30131f7300e1e7c67b69a9b0dde0006be87f1a10
extern const char sfs_assets_05_resistor_svg[];
#define SFS_05_resistor_svg_len 1120

// /assets/06_ntc.svg  SHA1:954bb1a5e0981b05c5519274b19454f0090e3421
extern const char sfs_assets_06_ntc_svg[];
#define SFS_06_ntc_svg_len 756

// /assets/07_ldr.svg  SHA1:8e00ddb489c534c6ed10dc6199edd8a948613125
extern const char sfs_assets_07_ldr_svg[];
#define SFS_07_ldr_svg_len 1124

// /assets/08_trailsensor.svg  SHA1:1ecfb31e4c5e0739e0c13b6e72a1df704e82225b
extern const char sfs_assets_08_trailsensor_svg[];
#define SFS_08_trailsensor_svg_len 915

// /assets/09_colorsensor.svg  SHA1:99c2e9151b6a5b0f276494f0e11d05f5dd5617a0
extern const char sfs_assets_09_colorsensor_svg[];
#define SFS_09_colorsensor_svg_len 996

// /assets/10_ultrasonic.svg  SHA1:5a1acc529b4aa36601df88cbb985705e98933ad2
extern const char sfs_assets_10_ultrasonic_svg[];
#define SFS_10_ultrasonic_svg_len 1641

// /assets/11_joystick.svg  SHA1:9a08ce4880f9390f06847728066a94d44d139010
extern const char sfs_assets_11_joystick_svg[];
#define SFS_11_joystick_svg_len 1438

// /assets/12_button.svg  SHA1:dde5c406a6cf8487699d292e95b600d57c6c9b3d
extern const char sfs_assets_12_button_svg[];
#define SFS_12_button_svg_len 882

// /assets/13_motor.svg  SHA1:0af38309093b08e04ed3f931993078f4f750abeb
extern const char sfs_assets_13_motor_svg[];
#define SFS_13_motor_svg_len 814

// /assets/14_servo.svg  SHA1:135eea4731b81269f52adc467635948579c37348
extern const char sfs_assets_14_servo_svg[];
#define SFS_14_servo_svg_len 1129

// /assets/15_rgbled.svg  SHA1:426cbbe9eb379d495c1095ec805719eac8e385f9
extern const char sfs_assets_15_rgbled_svg[];
#define SFS_15_rgbled_svg_len 981

// /assets/16_xmotor.svg  SHA1:5ba67e3e61fd01c67de8780627e5fe053f557dff
extern const char sfs_assets_16_xmotor_svg[];
#define SFS_16_xmotor_svg_len 2624

// /assets/17_tractor.svg  SHA1:cea0a787d62ffba1aa5b66884ccac06423ba15c2
extern const char sfs_assets_17_tractor_svg[];
#define SFS_17_tractor_svg_len 2549

// /assets/18_encoder.svg  SHA1:a003de2710c1f6ac273f7246cced8b37a0ea2f97
extern const char sfs_assets_18_encoder_svg[];
#define SFS_18_encoder_svg_len 2579

// /assets/19_lamp.svg  SHA1:e487fb742794ca36b8bc3cebcaceb3d293ed414b
extern const char sfs_assets_19_lamp_svg[];
#define SFS_19_lamp_svg_len 806

// /assets/20_xmmotor.svg  SHA1:0c46eb3abfb4cc8e6d08f171ec4cd464d78d5214
extern const char sfs_assets_20_xmmotor_svg[];
#define SFS_20_xmmotor_svg_len 2613

// /assets/21_lightbarrier.svg  SHA1:be3ec0fdc92b40c45c3e2312c2a555d1d39b52ae
extern const char sfs_assets_21_lightbarrier_svg[];
#define SFS_21_lightbarrier_svg_len 1172

// /assets/22_compressor.svg  SHA1:acdd34bc42fa2fa988772ff3195608e1a459237b
extern const char sfs_assets_22_compressor_svg[];
#define SFS_22_compressor_svg_len 850

// /assets/23_valve.svg  SHA1:022250c1073fe30a26789760393341ae5b2c80d4
extern const char sfs_assets_23_valve_svg[];
#define SFS_23_valve_svg_len 1012

// /assets/24_buzzer.svg  SHA1:880d1a2357b4d9a9c3768b1b4903a41d08fa43e4
extern const char sfs_assets_24_buzzer_svg[];
#define SFS_24_buzzer_svg_len 1583

// /assets/favicon.ico  SHA1:d40282686122ebb0dd7e70a12a623334300c64ae
extern const char sfs_assets_favicon_ico[];
#define SFS_favicon_ico_len 1279

// /assets/ftSwarm-8e21f0ef.svg  SHA1:18ed5b3001f043fbc0ba2b574545748c19d3e103
extern const char sfs_assets_ftSwarm_8e21f0ef_svg[];
#define SFS_ftSwarm_8e21f0ef_svg_len 2706

// /assets/index-4ac330c8.js  SHA1:f7a22d11d2cb351bcd1e9393506c769a7c032df0
extern const char sfs_assets_index_4ac330c8_js[];
#define SFS_index_4ac330c8_js_len 30042

// /assets/index-b078bf7b.css  SHA1:93adf540f257350e521aa778a1fb2ae4ff7a46c7
extern const char sfs_assets_index_b078bf7b_css[];
#define SFS_index_b078bf7b_css_len 1534
