
/**
 * @file sfs_files.h
 * @brief File list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script 
 *       in /panel. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

extern const char *sfs_get_file( char *filename, uint32_t *length );


// //index.html  SHA1:b2f6d7e0e7db0b196582020e0ca8d6678a7c0e53
extern const char sfs_index_html[];
#define SFS_index_html_len 373

// /assets/05_resistor.svg  SHA1:eb954ec2eb823671af139fc748170d6d50535cfe
extern const char sfs_assets_05_resistor_svg[];
#define SFS_05_resistor_svg_len 1120

// /assets/19_lamp.svg  SHA1:2cddd65e80f2560f73c76e415b81d433e26e297e
extern const char sfs_assets_19_lamp_svg[];
#define SFS_19_lamp_svg_len 806

// /assets/02_switch.svg  SHA1:355ecc7dabc8bee1a62791982936407afe1a4b00
extern const char sfs_assets_02_switch_svg[];
#define SFS_02_switch_svg_len 806

// /assets/17_tractor.svg  SHA1:6ae7f0e8a0730cafaaa0ccccae99e2a4b76fb197
extern const char sfs_assets_17_tractor_svg[];
#define SFS_17_tractor_svg_len 2549

// /assets/09_colorsensor.svg  SHA1:69b0d4d0b3ab34c872588fea7ced070fca84ee34
extern const char sfs_assets_09_colorsensor_svg[];
#define SFS_09_colorsensor_svg_len 996

// /assets/00_digital.svg  SHA1:9d40da710b2186347f9793f63637706b4877eae2
extern const char sfs_assets_00_digital_svg[];
#define SFS_00_digital_svg_len 729

// /assets/08_trailsensor.svg  SHA1:5fa3c0358dcb06a3b685c4113fa691d139edc9e9
extern const char sfs_assets_08_trailsensor_svg[];
#define SFS_08_trailsensor_svg_len 915

// /assets/16_xmotor.svg  SHA1:bbf9ff5b2a1da214aeaf5b3fe212ea622b9c486b
extern const char sfs_assets_16_xmotor_svg[];
#define SFS_16_xmotor_svg_len 2624

// /assets/04_voltage.svg  SHA1:c66c33753455334a7fd68507ca3c304980ddadfd
extern const char sfs_assets_04_voltage_svg[];
#define SFS_04_voltage_svg_len 874

// /assets/01_analog.svg  SHA1:a832843e3323945cecea98a242051a1bc3f1d69f
extern const char sfs_assets_01_analog_svg[];
#define SFS_01_analog_svg_len 1033

// /assets/18_encoder.svg  SHA1:71f6b5494596e12773baf1b52b70511a6d45f7b7
extern const char sfs_assets_18_encoder_svg[];
#define SFS_18_encoder_svg_len 2579

// /assets/14_servo.svg  SHA1:5e2cafcc4a4130049b12a3a62b49daf61bc75692
extern const char sfs_assets_14_servo_svg[];
#define SFS_14_servo_svg_len 1129

// /assets/03_reedswitch.svg  SHA1:1179be1d5d6daf5153c44438874e1dbf9f56755c
extern const char sfs_assets_03_reedswitch_svg[];
#define SFS_03_reedswitch_svg_len 1612

// /assets/11_joystick.svg  SHA1:bc1e465a3a41d51d6a31ba42c5c3ef88740cf965
extern const char sfs_assets_11_joystick_svg[];
#define SFS_11_joystick_svg_len 1438

// /assets/15_rgbled.svg  SHA1:3e4d51ea8b6b86bc94c5190a133bc9cf1144aad5
extern const char sfs_assets_15_rgbled_svg[];
#define SFS_15_rgbled_svg_len 981

// /assets/12_button.svg  SHA1:1d0be4dcea31939bb66537f669cb6f49db087130
extern const char sfs_assets_12_button_svg[];
#define SFS_12_button_svg_len 882

// /assets/07_ldr.svg  SHA1:6da32e37db8d8f5b4ec1b89a12e56f7d83706b1c
extern const char sfs_assets_07_ldr_svg[];
#define SFS_07_ldr_svg_len 1124

// /assets/06_ntc.svg  SHA1:61a1a3cca68d2cb50bfdf1ea31d3909376bc8532
extern const char sfs_assets_06_ntc_svg[];
#define SFS_06_ntc_svg_len 756

// /assets/10_ultrasonic.svg  SHA1:ccbb9645332696f1feb9c7b7caedc6e4aa0edcca
extern const char sfs_assets_10_ultrasonic_svg[];
#define SFS_10_ultrasonic_svg_len 1641

// /assets/13_motor.svg  SHA1:1cb2da56eb0a0c81bf8bd36312dab72c598d5d90
extern const char sfs_assets_13_motor_svg[];
#define SFS_13_motor_svg_len 814

// /css/app.6c010865.css  SHA1:0192c5b938302a951aee87234105da4517114ae0
extern const char sfs_css_app_6c010865_css[];
#define SFS_app_6c010865_css_len 1189

// /js/app.bc485fcb.js  SHA1:f5f546e034f7c7969836d8b3b4cc7f13cc6c08ea
extern const char sfs_js_app_bc485fcb_js[];
#define SFS_app_bc485fcb_js_len 4820

// /js/chunk-vendors.8f68e716.js  SHA1:d8a4d02bf807d0f8e64233d188d795b14464edc8
extern const char sfs_js_chunk_vendors_8f68e716_js[];
#define SFS_chunk_vendors_8f68e716_js_len 45739

// /js/app.bc485fcb.js.map  SHA1:a453a02a159c4193057050deadc7df9ee094a359
extern const char sfs_js_app_bc485fcb_js_map[];
#define SFS_app_bc485fcb_js_map_len 12520

// /js/chunk-vendors.8f68e716.js.map  SHA1:d7cf696269c8209d18c64a44e82c42f80961947b
extern const char sfs_js_chunk_vendors_8f68e716_js_map[];
#define SFS_chunk_vendors_8f68e716_js_map_len 214422
