[platformio]
boards_dir = boards/pio

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
    elektrofuzzis/ftSwarm
    pololu/VL53L0X
    electroniccats/MPU6050
    stm32duino/STM32duino LSM6DSR
    fastled/FastLED
    olikraus/U8g2

board_build.variants_dir = boards/variants
monitor_filters = esp32_exception_decoder

[env:ftSwarmRS]
board = ftSwarmRS

[env:ftSwarmRS-DE]
board = ftSwarmRS
build_flags = -D LANGUAGEDE

[env:ftSwarmRC]
board = ftSwarmRC

[env:ftSwarmRC-DE]
board = ftSwarmRC
build_flags = -D LANGUAGEDE

[env:ftSwarmJST]
board = ftSwarmJST

[env:ftSwarmJST-DE]
board = ftSwarmJST
build_flags = -D LANGUAGEDE

[env:ftSwarmXL]
board = ftSwarmXL

[env:ftSwarmXL-DE]
board = ftSwarmXL
build_flags = -D LANGUAGEDE

[env:ftSwarmControlUSBC]
board = ftSwarmControlUSBC

[env:ftSwarmControlUSBC-DE]
board = ftSwarmControlUSBC
build_flags = -D LANGUAGEDE

[env:ftSwarmControlUSBMicro]
board = ftSwarmControlUSBMicro

[env:ftSwarmControlUSBMicro-DE]
board = ftSwarmControlUSBMicro
build_flags = -D LANGUAGEDE

[env:ftSwarmPwrDrive]
board = ftSwarmPwrDrive

[env:ftSwarmPwrDrive-DE]
board = ftSwarmPwrDrive
build_flags = -D LANGUAGEDE

[env:ftSwarmDuino]
board = ftSwarmDuino

[env:ftSwarmDuino-DE]
board = ftSwarmDuino
build_flags = -D LANGUAGEDE
