
/**
 * @file sfs_files.h
 * @brief Brotli-compressed file list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script
 *       in /src/ide. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

// /index.html.br  SHA1:2d174ebe359f524e7dd7764e10db0e223ae91780
extern const char sfs_index_html_br[];
#define sfs_index_html_br_len 41920
