
/**
 * @file sfs_files.h
 * @brief Gzip-compressed file list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script
 *       in /src/ide. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

// /index.html.gz  SHA1:2acec8a49db4e36df3a1baf83f31494c4820a762
extern const char sfs_index_html_gz[];
#define sfs_index_html_gz_len 44983
