
/**
 * @file sfs_files.h
 * @brief Gzip-compressed file list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script
 *       in /src/ide. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

// /index.html.gz  SHA1:66c96ab0680a14f563a7a4e66c53f911973e9216
extern const char sfs_index_html_gz[];
#define sfs_index_html_gz_len 46265
