/*
 * SwOSHAL.h
 *
 * some useful hardware abstraction
 * 
 * (C) 2021/24 Christian Bergschneider & Stefan Fuss
 * 
 */
 
#pragma once

#include <driver/gpio.h>

// handle different plattforms
#if CONFIG_IDF_TARGET_ESP32S3
  #define xGPIO_NUM_22    GPIO_NUM_NC
  #define xGPIO_NUM_25    GPIO_NUM_NC
  #define xADC1_CHANNEL_8 ADC1_CHANNEL_8
  #define xGPIO_NUM_40    GPIO_NUM_40
  #define xGPIO_NUM_41    GPIO_NUM_41
  #define xGPIO_NUM_42    GPIO_NUM_42
  #define xGPIO_NUM_45    GPIO_NUM_45
  #define xGPIO_NUM_46    GPIO_NUM_46
  #define xGPIO_NUM_47    GPIO_NUM_47
  #define xGPIO_NUM_48    GPIO_NUM_48
#else
  #define xGPIO_NUM_22    GPIO_NUM_22
  #define xGPIO_NUM_25    GPIO_NUM_25
  #define xADC1_CHANNEL_8 ADC1_CHANNEL_MAX
  #define xGPIO_NUM_40    GPIO_NUM_NC
  #define xGPIO_NUM_41    GPIO_NUM_NC
  #define xGPIO_NUM_42    GPIO_NUM_NC
  #define xGPIO_NUM_45    GPIO_NUM_NC
  #define xGPIO_NUM_46    GPIO_NUM_NC
  #define xGPIO_NUM_47    GPIO_NUM_NC
  #define xGPIO_NUM_48    GPIO_NUM_NC
  #define ADC1_CHANNEL_8  ADC1_CHANNEL_MAX
  #define ADC1_CHANNEL_9  ADC1_CHANNEL_MAX
#endif

const int8_t GPIO_INPUT[9][8][3] = 
  { /* FTSWARMJST_1V0 */       { { GPIO_NUM_33, ADC_UNIT_1, ADC1_CHANNEL_5},   { xGPIO_NUM_25, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_26, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_27, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMCONTROL_1V3 */   { { GPIO_NUM_39, ADC_UNIT_1, ADC1_CHANNEL_3},   { xGPIO_NUM_25, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_26, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_27, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMJST_1V15 */      { { GPIO_NUM_39, ADC_UNIT_1, ADC1_CHANNEL_3},   { GPIO_NUM_32,  ADC_UNIT_1, ADC1_CHANNEL_4},   { GPIO_NUM_33, ADC_UNIT_1, ADC1_CHANNEL_5},   { GPIO_NUM_34, ADC_UNIT_1, ADC1_CHANNEL_6},   { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMRS_2V0 */        { { GPIO_NUM_1,  ADC_UNIT_1, ADC1_CHANNEL_0},   { GPIO_NUM_2,   ADC_UNIT_1, ADC1_CHANNEL_1},   { GPIO_NUM_8,  ADC_UNIT_1, ADC1_CHANNEL_7},   { GPIO_NUM_9,  ADC_UNIT_1, ADC1_CHANNEL_8},   { GPIO_NUM_11, ADC_UNIT_2, ADC2_CHANNEL_0},   { GPIO_NUM_13, ADC_UNIT_2, ADC2_CHANNEL_2},   { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMRS_2V1 */        { { GPIO_NUM_1,  ADC_UNIT_1, ADC1_CHANNEL_0},   { GPIO_NUM_2,   ADC_UNIT_1, ADC1_CHANNEL_1},   { GPIO_NUM_19, ADC_UNIT_2, ADC1_CHANNEL_8},   { GPIO_NUM_20, ADC_UNIT_2, ADC2_CHANNEL_9},   { GPIO_NUM_11, ADC_UNIT_2, ADC2_CHANNEL_0},   { GPIO_NUM_13, ADC_UNIT_2, ADC2_CHANNEL_2},   { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMCAM_3V12 */      { { GPIO_NUM_8,  ADC_UNIT_1, ADC1_CHANNEL_7},   { GPIO_NUM_9,   ADC_UNIT_1, ADC1_CHANNEL_8},   { GPIO_NUM_10, ADC_UNIT_2, ADC1_CHANNEL_9},   { GPIO_NUM_11, ADC_UNIT_2, ADC1_CHANNEL_0},   { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMPWRDRIVE_1V14 */ { { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC,  ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMDUINO_1V14 */    { { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC,  ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX}, { GPIO_NUM_NC, ADC_UNIT_1, ADC1_CHANNEL_MAX} },
    /* FTSWARMXL_1V00 */       { { GPIO_NUM_1,  ADC_UNIT_1, ADC1_CHANNEL_0},   { GPIO_NUM_2,   ADC_UNIT_1, ADC1_CHANNEL_1},   { GPIO_NUM_3, ADC_UNIT_1, ADC1_CHANNEL_2},    { GPIO_NUM_4,  ADC_UNIT_1, ADC1_CHANNEL_3},   { GPIO_NUM_5, ADC_UNIT_1, ADC1_CHANNEL_4},    { GPIO_NUM_8, ADC_UNIT_1, ADC1_CHANNEL_7},    { GPIO_NUM_10, ADC_UNIT_1, ADC1_CHANNEL_9},   { GPIO_NUM_9, ADC_UNIT_1, ADC1_CHANNEL_8}    }
  }; 

  /* USTX, PUA */
const gpio_num_t USTCPUA[9][2] = 
  { /* FTSWARMJST_1V0 */       { GPIO_NUM_NC,  GPIO_NUM_NC},
    /* FTSWARMCONTROL_1V3 */   { GPIO_NUM_15,  GPIO_NUM_14},
    /* FTSWARMJST_1V15 */      { GPIO_NUM_15,  GPIO_NUM_14},
    /* FTSWARMRS_2V0 */        { xGPIO_NUM_42, xGPIO_NUM_41},
    /* FTSWARMRS_2V1 */        { xGPIO_NUM_42, xGPIO_NUM_41},
    /* FTSWARMCAM_3V12 */      { GPIO_NUM_3,   GPIO_NUM_NC},
    /* FTSWARMPWRDRIVE_1V14 */ { GPIO_NUM_NC,  GPIO_NUM_NC},
    /* FTSWARMDUINO_1V14 */    { GPIO_NUM_NC,  GPIO_NUM_NC},
    /* FTSWARMXL_1V00 */       { GPIO_NUM_NC,  GPIO_NUM_NC}
  };   

const gpio_num_t GPIO_ACTOR[9][8][2] = 
  { /* FTSWARMJST_1V0 */      { { GPIO_NUM_13,  GPIO_NUM_4  }, { GPIO_NUM_2,   GPIO_NUM_0},   { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMCONTROL_1V3 */  { { GPIO_NUM_13,  GPIO_NUM_4  }, { GPIO_NUM_2,   GPIO_NUM_0},   { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMJST_1V15 */     { { GPIO_NUM_13,  GPIO_NUM_4  }, { GPIO_NUM_2,   GPIO_NUM_0},   { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMRS_2V0 */       { { GPIO_NUM_14,  GPIO_NUM_21 }, { xGPIO_NUM_45, xGPIO_NUM_46}, { GPIO_NUM_NC, GPIO_NUM_8},  { GPIO_NUM_NC, GPIO_NUM_9},  { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMRS_2V1 */       { { GPIO_NUM_14,  GPIO_NUM_21 }, { xGPIO_NUM_45, xGPIO_NUM_46}, { GPIO_NUM_NC, GPIO_NUM_8},  { GPIO_NUM_NC, GPIO_NUM_9},  { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMCAM_3V12 */     { { GPIO_NUM_40,  GPIO_NUM_41 }, { GPIO_NUM_1,   GPIO_NUM_2},   { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMPWRDRIVE_1V14*/ { { GPIO_NUM_NC,  GPIO_NUM_NC},  { GPIO_NUM_NC,  GPIO_NUM_NC},  { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMDUINO_1V14*/    { { GPIO_NUM_NC,  GPIO_NUM_NC},  { GPIO_NUM_NC,  GPIO_NUM_NC},  { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC}, { GPIO_NUM_NC, GPIO_NUM_NC} },
    /* FTSWARMXL_1V00*/       { { GPIO_NUM_16,  GPIO_NUM_15},  { GPIO_NUM_14,  GPIO_NUM_13},  { GPIO_NUM_11, GPIO_NUM_12}, { xGPIO_NUM_42, xGPIO_NUM_41}, { xGPIO_NUM_40, GPIO_NUM_39}, { GPIO_NUM_38, GPIO_NUM_37}, { GPIO_NUM_19, GPIO_NUM_20}, { GPIO_NUM_35, GPIO_NUM_36} }
  };   

const gpio_num_t SERVO[9][2] = 
  { /* FTSWARMJST_1V0 */       { xGPIO_NUM_25,  GPIO_NUM_NC},
    /* FTSWARMCONTROL_1V3 */   { GPIO_NUM_33,   GPIO_NUM_NC},
    /* FTSWARMJST_1V15 */      { xGPIO_NUM_25,  GPIO_NUM_NC},
    /* FTSWARMRS_2V0 */        { xGPIO_NUM_47,  GPIO_NUM_NC},
    /* FTSWARMRS_2V1 */        { xGPIO_NUM_47,  GPIO_NUM_15},
    /* FTSWARMCAM_3V12 */      { xGPIO_NUM_47,  GPIO_NUM_NC},
    /* FTSWARMPWRDRIVE_1V14 */ { GPIO_NUM_NC,   GPIO_NUM_NC},
    /* FTSWARMDUINO_1V14 */    { GPIO_NUM_NC,   GPIO_NUM_NC},
    /* FTSWARMXL_1V00 */       { GPIO_NUM_NC,   GPIO_NUM_NC}
  };

// CAMERA Pins
#define PWDN_GPIO_NUM     GPIO_NUM_NC
#define RESET_GPIO_NUM    GPIO_NUM_NC
#define XCLK_GPIO_NUM     GPIO_NUM_4
#define SIOD_GPIO_NUM     GPIO_NUM_18
#define SIOC_GPIO_NUM     GPIO_NUM_19
#define Y9_GPIO_NUM       GPIO_NUM_36
#define Y8_GPIO_NUM       GPIO_NUM_37
#define Y7_GPIO_NUM       GPIO_NUM_38
#define Y6_GPIO_NUM       GPIO_NUM_39
#define Y5_GPIO_NUM       GPIO_NUM_35
#define Y4_GPIO_NUM       GPIO_NUM_14
#define Y3_GPIO_NUM       GPIO_NUM_13
#define Y2_GPIO_NUM       GPIO_NUM_7
#define VSYNC_GPIO_NUM    GPIO_NUM_5
#define HREF_GPIO_NUM     GPIO_NUM_21
#define PCLK_GPIO_NUM     GPIO_NUM_20