
/**
 * @file sfs_files.h
 * @brief File list for the Web Server
 * @long This file contains the list of files that are available on the Web Server. It is generated by the build script 
 *       in /panel. It is not intended to be modified by the user.
 */

#pragma once
#include <stdint.h>

extern const char *sfs_get_file( char *filename, uint32_t *length );


// //index.html  SHA1:396529405ba981a5a426ca47ec6ea6e46cc51dfb
extern const char sfs_index_html[];
#define SFS_index_html 374

// /assets/05_resistor.svg  SHA1:65fb3d0ca53f7bdb37059d8bf4d6859777f8b823
extern const char sfs_assets_05_resistor_svg[];
#define SFS_05_resistor_svg 1120

// /assets/19_lamp.svg  SHA1:36794816d8035edcf1194b16f60c50f169d22249
extern const char sfs_assets_19_lamp_svg[];
#define SFS_19_lamp_svg 806

// /assets/02_switch.svg  SHA1:c72d36e908981227171d9a5ce1673b0f2dd31af2
extern const char sfs_assets_02_switch_svg[];
#define SFS_02_switch_svg 806

// /assets/17_tractor.svg  SHA1:5a55c09cc9ed2ae87e15e9a8986318ddb8f03809
extern const char sfs_assets_17_tractor_svg[];
#define SFS_17_tractor_svg 2549

// /assets/09_colorsensor.svg  SHA1:f7debd572e1d1275800d9761a29046a020d5a8f7
extern const char sfs_assets_09_colorsensor_svg[];
#define SFS_09_colorsensor_svg 996

// /assets/00_digital.svg  SHA1:5f0e8ce587da9866d3b5d03e4b65015818fd7e12
extern const char sfs_assets_00_digital_svg[];
#define SFS_00_digital_svg 729

// /assets/08_trailsensor.svg  SHA1:d1c9fef0a79b7c11265fb6c0979fc3f9be2b937e
extern const char sfs_assets_08_trailsensor_svg[];
#define SFS_08_trailsensor_svg 915

// /assets/16_xmotor.svg  SHA1:ef81a774ea12c741258f9a79f5e8fe571924c295
extern const char sfs_assets_16_xmotor_svg[];
#define SFS_16_xmotor_svg 2624

// /assets/04_voltage.svg  SHA1:77fef8f2de60acdc9d525dfd32b80ad706870cef
extern const char sfs_assets_04_voltage_svg[];
#define SFS_04_voltage_svg 874

// /assets/01_analog.svg  SHA1:d28922ed82bdec2bdccefc5a3945f174da4a1889
extern const char sfs_assets_01_analog_svg[];
#define SFS_01_analog_svg 1033

// /assets/18_encoder.svg  SHA1:df04ec210d53b53e79c668e80a685b67d9f40a00
extern const char sfs_assets_18_encoder_svg[];
#define SFS_18_encoder_svg 2579

// /assets/14_servo.svg  SHA1:14888ccc3d4645b97a8ccde61aed9b51b5b945aa
extern const char sfs_assets_14_servo_svg[];
#define SFS_14_servo_svg 1129

// /assets/03_reedswitch.svg  SHA1:c26b7b38897a31bcaedbd39292c7a566d67732dc
extern const char sfs_assets_03_reedswitch_svg[];
#define SFS_03_reedswitch_svg 1612

// /assets/11_joystick.svg  SHA1:814c8951731499dac34ea723dbe24f84b3c5f124
extern const char sfs_assets_11_joystick_svg[];
#define SFS_11_joystick_svg 1438

// /assets/15_rgbled.svg  SHA1:01781c78164b21cbff094c9e2620cc94b11449c8
extern const char sfs_assets_15_rgbled_svg[];
#define SFS_15_rgbled_svg 981

// /assets/12_button.svg  SHA1:6f327c3c3c43c033635f2cf41ea7a86d36a26717
extern const char sfs_assets_12_button_svg[];
#define SFS_12_button_svg 882

// /assets/07_ldr.svg  SHA1:42e791a06ccde31bf3977d23faab54dbf9caad72
extern const char sfs_assets_07_ldr_svg[];
#define SFS_07_ldr_svg 1124

// /assets/06_ntc.svg  SHA1:1af6cb6497dcf5ba7525bb6352309113c9dbd842
extern const char sfs_assets_06_ntc_svg[];
#define SFS_06_ntc_svg 756

// /assets/10_ultrasonic.svg  SHA1:dae75ca1c46dfc5f70dc692d79047cc5e66f863c
extern const char sfs_assets_10_ultrasonic_svg[];
#define SFS_10_ultrasonic_svg 1641

// /assets/13_motor.svg  SHA1:3b339f8f79ffe7daa2544e84f0e738795fbe9a46
extern const char sfs_assets_13_motor_svg[];
#define SFS_13_motor_svg 814

// /css/app.f36d1a27.css  SHA1:4c2dcda467a81dffb133e3b3c7c2d9a01dba20c7
extern const char sfs_css_app_f36d1a27_css[];
#define SFS_app_f36d1a27_css 1081

// /js/chunk-vendors.8057569b.js.map  SHA1:c0adca6b56ff8b02e74d5255e8737142f856f342
extern const char sfs_js_chunk-vendors_8057569b_js_map[];
#define SFS_chunk-vendors_8057569b_js_map 163629

// /js/app.0c6e5732.js.map  SHA1:01d6d28d367f0c644383f7139e346b55620a7104
extern const char sfs_js_app_0c6e5732_js_map[];
#define SFS_app_0c6e5732_js_map 10934

// /js/chunk-vendors.8057569b.js  SHA1:a561881ffc8246f9f8805a5fec0586f08c5487a9
extern const char sfs_js_chunk-vendors_8057569b_js[];
#define SFS_chunk-vendors_8057569b_js 28158

// /js/app.0c6e5732.js  SHA1:7101b207e5a4e140efce4342ff740ee9d5faa227
extern const char sfs_js_app_0c6e5732_js[];
#define SFS_app_0c6e5732_js 3834
